### ISSUE TITLE
Allow for the user to chose specific days that they dont want to be notified about.

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/HotelPriceScout#126]
This could be done by having a list of choosable days on the settings page. These days would then be made into a list in the scout and would be parsed into the comparators. Then, when the comparator is going to send a notification, the list of days to be not be notified about can be sorted out of the list which contains the days with discrepancies. Note that this could mean that the list is empty  and therefore that no notification should be sent even though we have previously decided that it should be sent. We could therefore in SendNotification check that if the list is empty, we dont continue with the rest of the function. A way to circumvent this is in the CheckDiscrepancy method. Here we can before we assign the booleans, have an if-statement that checks if the date is found in the list of days that should not be notified about. Keep in mind that the CheckDiscrepancy method is run for three months worth of dates, where the notification should only be sent for days in one month. Therefore most of these checks in CheckDiscrepancy would be unnecessay, BUT it is nonetheless still more suitable to do it there than in SendNotification since we should only enter the SendNotification method when we are sure that a notification should be sent.

**Comment by KarmaKamikaze** [comment]
Keep in backlog for report.
